name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d4bbde063b40c5a1759fb96d106a409b08731be6e03bcf1348b80fddbd5fb08"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
