name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40291c0b3bb260b4e9feb04f8fa641258ac56b19da8edaa207e45250e6bf0742"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
