name = "MCC"
author = "Slash"
version = "0.9.54"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41f1c22465389b170e32d7c1cae2750b2550466c2413e448963d0d58d2475cbc"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
