name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "927aadd956721592b0ea8c26cde5e0ebf588b47168f106dd6431ff9ad8f3c9a8"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
