name = "TBA"
author = "Slash"
version = "0.9.75"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e7a0660f08f84ab847e7f42d752780d56d1fed1715cd2b89ea13fe1a4df218e"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
