name = "MCC"
author = "Slash"
version = "0.9.29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71f82995d727ac3ba102e08bc5a33a326f85afbacc33598f505a6f55bd48b8d4"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
