name = "TBA"
author = "Slash"
version = "0.9.80"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef5cf69708547b95f2a74406288c563a6bf29f5ed6dc5a175f64328845aac955"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
