name = "MCC"
author = "Slash"
version = "0.9.50"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2acc4d1d0d8c26f820bcd1d841564046521e9cc343ab979f1dd6e9723aa90618"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
