name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7e15fc630d7f5fbf92d238030b7f0e06147b415575a8a5e1cca3c44393baf59"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
