name = "TBA"
author = "Slash"
version = "0.9.67"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "321e815a06d93ac01bc5c44bb1546e7288a39426ce29ee648783085cc1a1a580"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
