name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "420006118edb7c732ed0b08b551df0a8a5d5c9f8cec7ea832a562062086dd739"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
