name = "MCC"
author = "Slash"
version = "0.9.61"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cee1ed30314a852f2a722583fbaef03dc3ee679d7c4db2e503a50de225103aa4"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
