name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea9bdbbdd3d5da2085186459c941f1a17f3567c01d42ba99d6737773b0279e00"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
