name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "668aa463f0a0c25729e34b069e8b0ad0c1be8857209c2bc8c8b9a9768972fadd"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
