name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d6053dda51a218f501903c67fd0aa8e04e07a8696912925fab414cbfeaedeae"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
