name = "TBA"
author = "Slash"
version = "0.9.75"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33d2dbe5c50c6f48f345d82ef7dc61f983db0c00f8f84730d9f1d3afe489e40b"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
