name = "MCC"
author = "Slash"
version = "0.9.43"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c11226457dc4c7592dd298b78dfa9faccaed9138dd35991f9216c89292ed11af"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
